# Generated by Django 5.1.4 on 2025-01-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='file_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
